config/routes.rb
FirstApp::Application.routes.draw do
  devise_for :usuarios do
    get "/logout" => "devise/sessions#destroy", :as => "logout"
  end

  root :to => 'application#index'
  post "/lista/create" => "lista_emails#create", :as => "create_lista_email"
  

end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
  has_many :usuario_grupos
  has_many :topicos
  has_many :usuarios, :through => :usuario_grupos
  belongs_to :dono, :class_name => 'Usuario'
  validates :dono, :presence => true
  validates :nome, :presence => true
end

app/models/lista_email.rb
class ListaEmail < ActiveRecord::Base
  def valida_email
    (self.email =~ /\w+@\w+\.\w+/) != nil
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topico
  belongs_to :usuario

  validates :topico, :presence => true
  validates :usuario, :presence => true

end

app/models/topico.rb
class Topico < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :grupo

  has_many :posts
  
  validates :grupo , :presence => true
  validates :titulo, :presence => true
  validates :usuario, :presence => true

  validates :posts, :presence => true

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  #  has_and_belongs_to_many :grupos
  has_many :usuario_grupos
  has_many :grupos, :through => :usuario_grupos
  has_many :grupos_gerenciados, :class_name => 'Grupo', :foreign_key => 'dono_id'
end

app/models/usuario_grupo.rb
class UsuarioGrupo < ActiveRecord::Base
  belongs_to :grupo
  belongs_to :usuario
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def index
    @lista_email = ListaEmail.new
    @landing_page = false
  end
end

app/controllers/lista_emails_controller.rb
# coding: utf-8

class ListaEmailsController < ApplicationController
  
  def create
    @lista_email = ListaEmail.new params[:lista_email]
    if @lista_email.valida_email
      @lista_email.save
      redirect_to root_path, :notice => "E-mail cadastrado com sucesso!!"
    else
      redirect_to root_path, :alert => "E-mail inválido!!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_emails_helper.rb
module ListEmailsHelper
end

app/helpers/lista_emails_helper.rb
module ListaEmailsHelper
end

app/helpers/lista_helper.rb
module ListaHelper
end

app/views/application/index.html.erb
<% if @landing_page %>
  <%= form_for @lista_email, :url => create_lista_email_path do |f| %>
    <%=  f.label :email, "E-mail:"  %>
    <%=  f.text_field :email  %><br/><br/>
    <%= f.submit "Enviar" , :class => "ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" %>
  <%  end %>
<% end %>
<%= link_to "Cadastro", new_usuario_registration_path %>
<% if current_usuario %>
  <%= link_to "Logout", logout_path %>
<%  else %>
  <%= link_to "Login", new_usuario_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grupo de Estudos Online</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag "jquery-1.6.2.min.js" %>
    <%= javascript_include_tag "jquery-ui-1.8.16.custom.min" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="conteudo" align="center">
      <img src="images/workgroup.gif" alt="Grupo de Estudos Online" id="logogeo" />
      <div class="notice"><%= notice if notice %></div>
      <div class ="alert"><%= alert if alert %></div>
      <%= yield %>
    </div>
  </body>
</html>